# Generated by Django 4.1.10 on 2023-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_clientes_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logins',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
