# Generated by Django 4.1.10 on 2023-08-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_clientes_ativo_alter_logins_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logins',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
