# Generated by Django 4.1.10 on 2023-08-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_clientes_ativo_alter_logins_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='logins',
            name='ativo',
        ),
    ]
