# Generated by Django 4.1.10 on 2023-08-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_clientes_ativo_remove_logins_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('id_login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='core.logins')),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
