# Generated by Django 4.1.10 on 2023-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_delete_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='teste',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
