# Generated by Django 4.1.10 on 2023-08-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_logins_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logins',
            name='teste',
        ),
    ]
